import {
  APPLICATION_CASES,
  CATALOG_CATEGORIES as SCENA_CATEGORIES,
  CATALOG_PRODUCTS as SCENA_PRODUCTS,
  FAQS,
} from '@/lib/catalog'
import {
  CATALOG_CATEGORIES as KEATON_CATEGORIES,
  CATALOG_PRODUCTS as KEATON_PRODUCTS,
} from '@/lib/keaton-generated'

export const CATALOG_CATEGORIES = [...SCENA_CATEGORIES, ...KEATON_CATEGORIES]
export const CATALOG_PRODUCTS = [...SCENA_PRODUCTS, ...KEATON_PRODUCTS]

export { APPLICATION_CASES, FAQS }
